Repository graeter-group/kimmdy, pull requests merged in 2024-03, with the labels that each got.

#396 feat: allow customizing trjconv output group
  .github/workflows/build-docs.yml
  src/kimmdy/analysis.py
Labels: testthis

#399 fix: squiggly lines begone
  _reference/analysis.qmd
  _reference/coordinates.qmd
  _reference/recipe.qmd
  _reference/runmanager.qmd
  docs/_reference/analysis.html
  docs/_reference/coordinates.html
  docs/_reference/recipe.html
  docs/_reference/runmanager.html
  docs/guide/explanation/index.html
  docs/guide/how-to/index.html
  docs/guide/tutorials/getting-started.html
  docs/guide/tutorials/index.html
  docs/listings.json
  docs/search.json
  docs/sitemap.xml
  guide/tutorials/analyse-extended-simulations/analyse_kimmdy_migration.py
  guide/tutorials/colbuilder-files/change_crosslink_atom_names.py
  src/kimmdy/analysis.py
  src/kimmdy/cmd.py
  src/kimmdy/config.py
  src/kimmdy/coordinates.py
  src/kimmdy/kmc.py
  src/kimmdy/parsing.py
  src/kimmdy/plugins.py
  src/kimmdy/recipe.py
  src/kimmdy/runmanager.py
  src/kimmdy/schema.py
  src/kimmdy/tasks.py
  src/kimmdy/tools.py
  src/kimmdy/topology/topology.py
  src/kimmdy/utils.py
  tests/test_parsing.py
  tests/test_recipe.py
  tests/test_topology.py
Labels: testthis

#408 feat: add focus to grappa parameterizer
  _reference/plugins.qmd
  docs/_reference/plugins.html
  docs/guide/explanation/index.html
  docs/guide/how-to/index.html
  docs/guide/tutorials/getting-started.html
  docs/guide/tutorials/index.html
  docs/search.json
  docs/sitemap.xml
  src/kimmdy/kimmdy-yaml-schema.json
  src/kimmdy/plugins.py
  src/kimmdy/runmanager.py
  src/kimmdy/topology/topology.py
  tests/test_integration.py
Labels: testthis, docthis

#413 Analysis fixes
  _reference/analysis.qmd
  _reference/kmc.qmd
  _reference/recipe.qmd
  _reference/tasks.qmd
  _reference/topology.atomic.qmd
  docs/_reference/analysis.html
  docs/_reference/kmc.html
  docs/_reference/recipe.html
  docs/_reference/tasks.html
  docs/_reference/topology.atomic.html
  docs/guide/explanation/index.html
  docs/guide/how-to/index.html
  docs/guide/tutorials/getting-started.html
  docs/guide/tutorials/index.html
  docs/search.json
  docs/sitemap.xml
  src/kimmdy/analysis.py
Labels: docthis

#414 fix: don't discover stepXX.pdb's gromacs produces sometimes
  docs/guide/explanation/index.html
  docs/guide/how-to/index.html
  docs/guide/tutorials/getting-started.html
  docs/guide/tutorials/index.html
  docs/sitemap.xml
  src/kimmdy/runmanager.py
Labels: bug, testthis
